name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4

      - name: Working dir after checkout
        run: ls -al

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo 2
        run: echo "Hola mundo desde mi segundo job y mi segundo paso"