name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      NAME: CodigoFacilito

    steps:
      - name: Echo messages
        id: step_uno
        run: echo "my_variable=Hola mundo guardado dede el job" >> $GITHUB_OUTPUT

      - name: Obtener mensaje
        run: echo "El mensaje es:${{steps.step_uno.outputs.my_variable}}"

  second_job:
    name: Second Job CodigoFacilito
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo 2
        run: echo "Hola mundo desde mi segundo job y mi segundo paso"