name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      SALIDA: ${{ steps.step1.outputs.my_variable }}

    steps:
    - name: Generar archivo
      id: stepUno
      run: 
        echo "Archivo prueba, hola" >> test.log

    - name: Subir artefacto
      uses: actions/upload-artifact@v4
      with:
        name: test-log
        path: test.log