name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  first_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["Hola", "CodigoFacilito", "Bootcamp Actions"]

    steps:
    - name: Print message
      run: |
        echo "${{ matrix.message }}" 
    
    